### PR TITLE
 resolve error

### PR DESCRIPTION
**Pull request by Mrjojono**
This pull request adds a new course to the `courses/introduction_aux_reseaux_informatiques_avec_cisco_beginner_fr_eazytraining.yaml` file. The course is focused on introducing Cisco networking for beginners and includes various details about the course.

Key changes:

* Added course details including `id`, `name`, `url`, `duration_hours`, `level`, `objectives`, and `description`.
* Included prerequisites for the course, specifying the necessary background knowledge.
* Listed the technologies covered in the course, notably Cisco Packet.
* Set the language of the course to French and marked it as not deprecated.

### CODE REVIEW

**Comment by diranetafen** [comment]
Hello
essaie de synchroniserta branche avec la mainstream comme ce que j'ai fait dans la vidéo sur slack, elle intègre de nouvelles technos et corrige le souci de error file format

**Comment by Mrjojono** [comment]
Bien recu !

**Comment by diranetafen** [comment]
synchronise sans modifier de fichier stp
tu peux refaire cette PR

**Comment by Mrjojono** [comment]
Bien recu !

**Comment by diranetafen** [comment]
ce cours est déjà existant

**Pull request closed without merging**
